INSERT INTO bull_schema_shit.heckingusers (id, user_name, user_password) VALUES (1, 'admin', 'pas');
INSERT INTO bull_schema_shit.heckingusers (id, user_name, user_password) VALUES (2, 'client', 'pas');

INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (1, 1, '123');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (2, 1, 'test message');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (3, 1, 'dfg');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (4, 1, 'dfgh');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (5, 1, 'dfgh');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (6, 1, 'sdfgh');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (7, 1, 'jk;l');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (8, 1, 'k'';l');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (9, 1, 'kj;');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (10, 1, 'jk;');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (11, 1, 'k'';l');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (12, 1, 'kl'';');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (13, 1, 'kj;');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (14, 1, 'jk;');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (15, 1, 'jk;l');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (16, 1, '[[[');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (17, 1, 'zxv');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (18, 1, 'ghk');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (19, 1, 'jkl;');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (20, 1, 'фывфып');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (21, 1, 'sdfg');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (22, 2, 'Hello, i''m Client');
INSERT INTO bull_schema_shit.whattheheck (id, id_user, text_message) VALUES (23, 1, 'Hello, I''m Admin');